#!/bin/bash

set -e

for SIZE in 16 22 24 32 48 64 ; do
	xdg-icon-resource uninstall --theme ubuntu-mono-dark --size ${SIZE} emojione-picker
	xdg-icon-resource uninstall --theme ubuntu-mono-light --size ${SIZE} emojione-picker
done

